---
apiVersion: xl-deploy/v1
kind: Environments
spec:
- name: Environments/Dictionaries
  type: core.Directory
- name: Environments/Hotelbeds
  type: core.Directory
- name: Environments/Dictionaries/Hotelbeds
  type: core.Directory
- name: Environments/Dictionaries/Hotelbeds/hotelbeds-dev
  type: udm.Dictionary
  entries:
    bdd.url: jdbc:mysql://localhost:3306/congruencias
    bdd.user: cng_user
    smoke.test.url: http://localhost:8080/congruencias/index
    url.webservices: http://localhost:8080/axis2/services/webservices.webservicesHttpEndpoint/
  encryptedEntries:
    bdd.pass: cng_password
- name: Environments/Dictionaries/Hotelbeds/hotelbeds-pre
  type: udm.Dictionary
  entries:
    bdd.url: jdbc:mysql://localhost:3306/congruencias
    bdd.user: cng_user
    smoke.test.url: http://localhost:8080/congruencias/index
    url.webservices: http://localhost:8080/axis2/services/webservices.webservicesHttpEndpoint/
  encryptedEntries:
    bdd.pass: cng_password
- name: Environments/Dictionaries/Hotelbeds/hotelbeds-pro
  type: udm.Dictionary
  entries:
    bdd.url: jdbc:mysql://localhost:3306/congruencias
    bdd.user: cng_user
    smoke.test.url: http://localhost:8080/congruencias/index
    url.webservices: http://localhost:8080/axis2/services/webservices.webservicesHttpEndpoint/
  encryptedEntries:
    bdd.pass: cng_password
- name: Environments/Hotelbeds/hotelbeds-dev
  type: udm.Environment
  members:
  - Infrastructure/Hotelbeds/host-dev/axis2
  - Infrastructure/Hotelbeds/host-dev/mysql-cli
  - Infrastructure/Hotelbeds/host-dev/smokeTest
  - Infrastructure/Hotelbeds/host-dev/tomcat/virtual-host-congruencias
  dictionaries:
  - Environments/Dictionaries/Hotelbeds/hotelbeds-dev
- name: Environments/Hotelbeds/hotelbeds-pre
  type: udm.Environment
  members:
  - Infrastructure/Hotelbeds/host-pre/axis2
  - Infrastructure/Hotelbeds/host-pre/mysql-cli
  - Infrastructure/Hotelbeds/host-pre/smokeTest
  - Infrastructure/Hotelbeds/host-pre/tomcat/virtual-host-congruencias
  dictionaries:
  - Environments/Dictionaries/Hotelbeds/hotelbeds-pre
- name: Environments/Hotelbeds/hotelbeds-pro
  type: udm.Environment
  members:
  - Infrastructure/Hotelbeds/host-pro-1/axis2
  - Infrastructure/Hotelbeds/host-pro-1/mysql-cli
  - Infrastructure/Hotelbeds/host-pro-1/smokeTest
  - Infrastructure/Hotelbeds/host-pro-1/tomcat/virtual-host-congruencias
  - Infrastructure/Hotelbeds/host-pro-2/axis2
  - Infrastructure/Hotelbeds/host-pro-2/mysql-cli
  - Infrastructure/Hotelbeds/host-pro-2/smokeTest
  - Infrastructure/Hotelbeds/host-pro-2/tomcat/virtual-host-congruencias
  - Infrastructure/Hotelbeds/host-pro-3/axis2
  - Infrastructure/Hotelbeds/host-pro-3/mysql-cli
  - Infrastructure/Hotelbeds/host-pro-3/smokeTest
  - Infrastructure/Hotelbeds/host-pro-3/tomcat/virtual-host-congruencias
  - Infrastructure/Hotelbeds/host-pro-4/axis2
  - Infrastructure/Hotelbeds/host-pro-4/mysql-cli
  - Infrastructure/Hotelbeds/host-pro-4/smokeTest
  - Infrastructure/Hotelbeds/host-pro-4/tomcat/virtual-host-congruencias
  dictionaries:
  - Environments/Dictionaries/Hotelbeds/hotelbeds-pro
